name: Deploy Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment directory (non-prod/prod)'
        required: true
      parameter_file:
        description: 'Parameter file name in the environment directory (e.g., dev-parameters.json)'
        required: true
      resource_group_name:
        description: 'Resource group to deploy to'
        required: true
      location:
        description: 'Azure location for the deployment (overrides parameter file location if provided)'
        required: false

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Bicep Linter
      run: |
        az bicep build --file env/${{ github.event.inputs.environment }}/main.bicep

  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Validate Parameters
      run: |
        az deployment group validate \
          --resource-group ${{ github.event.inputs.resource_group_name }} \
          --template-file env/${{ github.event.inputs.environment }}/main.bicep \
          --parameters @env/${{ github.event.inputs.environment }}/${{ github.event.inputs.parameter_file }}

  preview:
    runs-on: ubuntu-latest
    needs: [lint, validate]
    steps:
    - uses: actions/checkout@v3
    - name: Deployment Preview
      run: |
        az deployment group what-if \
          --resource-group ${{ github.event.inputs.resource_group_name }} \
          --template-file env/${{ github.event.inputs.environment }}/main.bicep \
          --parameters @env/${{ github.event.inputs.environment }}/${{ github.event.inputs.parameter_file }}

