name: Deploy Environment
concurrency: az-trial-infra

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment directory (non-prod/prod)'
        required: true
        default: 'non-prod'
      parameter_file:
        description: 'Parameter file name in the environment directory (e.g., dev-parameters.json)'
        required: true
      resource_group_name:
        description: 'Resource group to deploy to'
        required: true
      location:
        description: 'Azure location for the deployment (overrides parameter file location if provided)'
        required: false
        default: ''
      debug:
        description: 'Enable debug mode for additional output'
        required: false
        default: 'false'

permissions:
  id-token: write
  contents: read

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Ensure Linter Configuration is Available
      run: |
        echo "Contents of bicepconfig.json:"
        cat ./deploy/bicepconfig.json
    - name: Run Bicep Linter
      run: |
        echo "Running Bicep Linter for env/${{ github.event.inputs.environment }}/main.bicep..."
        az bicep build --file env/${{ github.event.inputs.environment }}/main.bicep
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
    - name: Parameter Validation
      run: |
        echo "Validating parameters for environment ${GITHUB_EVENT_INPUTS_ENVIRONMENT}..."
        az deployment group validate \
          --resource-group ${{ github.event.inputs.resource_group_name }} \
          --template-file env/${{ github.event.inputs.environment }}/main.bicep \
          --parameters @env/${{ github.event.inputs.environment }}/${{ github.event.inputs.parameter_file }} \
          $(if [ -n "${{ github.event.inputs.location }}" ]; then echo "--parameters location=${{ github.event.inputs.location }}"; fi)

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, validate]
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
    - name: Deploy Environment Template
      run: |
        echo "Deploying Bicep template for ${GITHUB_EVENT_INPUTS_ENVIRONMENT} environment..."
        az deployment group create \
          --resource-group ${{ github.event.inputs.resource_group_name }} \
          --template-file env/${{ github.event.inputs.environment }}/main.bicep \
          --parameters @env/${{ github.event.inputs.environment }}/${{ github.event.inputs.parameter_file }} \
          $(if [ -n "${{ github.event.inputs.location }}" ]; then echo "--parameters location=${{ github.event.inputs.location }}"; fi)

  debug:
    if: ${{ github.event.inputs.debug == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Debug Directory Structure
      run: |
        echo "Debugging directory structure..."
        ls -R
    - name: Display Parameters
      run: |
        echo "Parameters file content:"
        cat env/${{ github.event.inputs.environment }}/${{ github.event.inputs.parameter_file }}

