name: Deploy Module

on:
  workflow_dispatch:
    inputs:
      resource_group_name:
        description: 'Resource group to deploy to'
        required: true
      module_path:
        description: 'Path to the module Bicep file (e.g., modules/storage-account/main.bicep)'
        required: true
      parameters_file:
        description: 'Optional path to a parameters.json file'
        required: false
      manual_parameters:
        description: 'Comma-separated key=value pairs for manual parameters (e.g., baseName=myapp,location=eastus)'
        required: false

jobs:
  deploy-module:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Parse Parameters
      if: ${{ github.event.inputs.manual_parameters }}
      run: |
        echo "::set-output name=params::$(echo '${{ github.event.inputs.manual_parameters }}' | sed 's/,/ --parameters /g')"

    - name: Deploy Module
      run: |
        az deployment group create \
          --resource-group ${{ github.event.inputs.resource_group_name }} \
          --template-file ${{ github.event.inputs.module_path }} \
          $(if [ -n "${{ github.event.inputs.parameters_file }}" ]; then echo "--parameters @${{ github.event.inputs.parameters_file }}"; fi) \
          $(if [ -n "${{ steps.parse-parameters.outputs.params }}" ]; then echo "--parameters ${{ steps.parse-parameters.outputs.params }}"; fi)

