name: Deploy Storage Account

on:
  workflow_dispatch:
    inputs:
      resource_group_name:
        description: 'The name of the resource group to deploy to'
        required: true
      base_name:
        description: 'Base name for the storage account (will have a unique suffix)'
        required: true
      location:
        description: 'The Azure location for the storage account'
        required: false
        default: 'eastus'

jobs:
  deploy-modules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Storage Account
      run: |
        az deployment group create \
          --resource-group ${{ github.event.inputs.resource_group_name }} \
          --template-file modules/storage-account/main.bicep \
          --parameters baseName=${{ github.event.inputs.base_name }} \
                       location=${{ github.event.inputs.location }}

