name: List Resource Groups

on: [workflow_dispatch]

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | bash

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # validate and list relevant info
      - name: Show Subscription Name
        run: |
          az account show --query "{SubscriptionName:name}" -o json

      - name: Show Available Resource Groups
        run: |
          az group list --query "[].name" -o table
